version: '3.2'
services:
  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: "${POSTGRESQL_USER}"
      POSTGRES_PASSWORD: "${POSTGRESQL_PASSWORD}"
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
  web:
    build: .
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    command: /bin/bash -c "rm -f /tmp/server.pid && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid"
    depends_on:
      - db
    networks:
      - default
networks:
  default:
volumes:
  db-data:
    driver: local
