default: &default
  adapter: postgresql
  # adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRESQL_USER"] || ENV["USER"] || 'postgres' %>
  database: <%= ENV["POSTGRESQL_DATABASE"] || 'api-service_development' %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  host: <%= ENV["POSTGRESQL_HOST"] || 'localhost' %>
  pool: <%= ENV["POSTGRESQL_POOL"] || 5 %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5433 %>

development:
  <<: *default

test:
  <<: *default
  database: api-service_test

production:
  <<: *default
  pool: 15
