name: Deploy

on:
  push:
    branches:
      - master
      - qa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rubocop checks
        uses: luizfonseca/github-actions-rubocop@1.5.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      - name: Deploy to staging
        if: github.ref == 'refs/heads/qa'
        uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_app_name: ${{ secrets.HEROKU_STG_APP_NAME }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
      - name: Run migrations
        run: |
          rake db:migrate
      - name: Deploy to production
        if: github.ref == 'refs/heads/master'
        uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_app_name: ${{ secrets.HEROKU_PRD_APP_NAME }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ${{ secrets.SLACK_CHANNEL }}
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ${{ secrets.SLACK_CHANNEL }}
          status: FAILED
          color: danger
